### ISSUE TITLE
On interpolation mode only sentences from the same survey may be selected

### ISSUE THREAD

**Issue by ianneidel** [kaijagahm/ygdpDashboard#44]
On interpolation mode, only sentences from the selected survey may be used. For example, if I am using a survey 11 sentence for sentence 1 I cannot use any sentences from survey 6 for sentence 2. Unlike for points mode, I think we should be able to easily compare across surveys (e.g. by introducing a survey dropdown for every subsequent sentence selection).

**Comment by kaijagahm** [comment]
On 3/10, Jim told me he wanted me to prioritize fixing this, and it turned out to be a pretty easy fix.

Fixed this in commit https://github.com/kaijagahm/ygdpDashboard/commit/fc09c4351dc0e0aecbfe11dee5763e30fa6aa705 and another adjacent one.

Deployed the app with this fix on 3/12.
